/* eslint-disable @typescript-eslint/ban-ts-comment */
import React from 'react'
import { SearchContext } from '../context/searchContext'
import Head from 'next/head'
import '@material/layout-grid/dist/mdc.layout-grid.css'
import Grid from '@mui/material/Grid'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import '@material/button/dist/mdc.button.css'
import Card from '@mui/material/Card'
import { CardContent, Typography, CardMedia } from '@mui/material'
import styles from '../styles/Home.module.css'
import { MdOutlineArticle } from 'react-icons/md'
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  // @ts-ignore
  const { setStoredValue } = React.useContext(SearchContext)

  React.useEffect(() => {
    setStoredValue({
      positive: undefined,
      fiveDays: undefined,
      zipCode: '',
    })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Grid container style={{ minHeight: '100vh' }}>
            <Grid item xs={12} sm={12} md={6} lg={6} xl={6}>
              <Card
                sx={{ boxShadow: '0' }}
                style={{ backgroundColor: '#f3de00' }}
              >
                <Link href="/">
                  <Image
                    src="/header.png"
                    alt="header"
                    width={568}
                    height={152}
                  />
                </Link>
              </Card>

              <Card
                variant="outlined"
                sx={{
                  borderRadius: '20px',
                  backgroundColor: '#472B77',
                  color: 'white',
                }}
              >
                <CardContent>
                  <Typography gutterBottom variant="h3" component="div">
                    Need Free Treatment for Covid-19?
                  </Typography>

                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="center"
                  >
                    <Grid xs={1} item></Grid>
                    <Grid xs={2} item>
                      <MdOutlineArticle className={styles.roundedIcon} />
                    </Grid>
                    <Grid xs={9} item sx={{ paddingLeft: '1rem' }}>
                      <Typography variant="h5" component="div">
                        COVID-19 Treatment Assessment
                      </Typography>
                      <Typography variant="body2">
                        Take this 5-min quick assessment.
                      </Typography>
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>

              <Grid
                container
                direction="row"
                justifyContent="space-between"
                alignItems="flex-end"
                sx={{
                  margin: '2rem 0',
                }}
              >
                <Grid xs={7} item></Grid>
                <Grid xs={5} item>
                  <Link href="/assessment" passHref>
                    <Button variant="contained" className={styles.clickHere}>
                      Click Here
                    </Button>
                  </Link>
                </Grid>
              </Grid>
            </Grid>
            <Box
              component={Grid}
              item
              md={6}
              display={{ xs: 'none', sm: 'none', md: 'flex' }}
            >
              <Card
                sx={{
                  width: '100%',
                  height: '100%',
                  border: '0',
                  boxShadow: '0',
                }}
              >
                <CardMedia
                  sx={{ height: '100%', backgroundSize: 'cover' }}
                  image="/testit.png"
                  title="header"
                />
              </Card>
            </Box>
          </Grid>
        </div>
      </main>
    </div>
  )
}
